INSERT INTO FILM (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA_ID)
VALUES ('Film', 'Description', '2000-01-01', 100, 4, 1);

INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('test@test.ru', 'test', 'test', '2000-01-01');

INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('test1@test.ru', 'test1', 'test1', '1999-01-01');

INSERT INTO LIKES (FILM_ID, USER_ID)
VALUES (1, 2);